AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceKey:
    Type: String
    Description: Key for the instance
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0aa7d40eeae50c9a9 
      InstanceType: t2.micro
      SubnetId: subnet-084bb511a8d8eb976
      KeyName: !Ref InstanceKey